### ISSUE TITLE
Exception when deploying chaincode 

### ISSUE THREAD

**Issue by chris-cyliu** [ooibc88/FabricSharp#4]
Hi, I would like to try FabricSharp. I compiled the peer image and orderer image. When I deploying the custom chaincode provided in Readme before invoking the chaincode function, an exception occured in peer nodes . Would you please help me to take a look? Thank you

Branch: sigmod20

Orderer Log:
```
2021-01-24 09:36:59.688 UTC [orderer/consensus/kafka] setupProducerForChannel -> INFO 01b [channel: newchaincode] Setting up the producer for this channel...
2021-01-24 09:36:59.690 UTC [orderer/consensus/kafka] startThread -> INFO 01c [channel: newchaincode] Producer set up successfully
2021-01-24 09:36:59.690 UTC [orderer/consensus/kafka] sendConnectMessage -> INFO 01d [channel: newchaincode] About to post the CONNECT message...
2021-01-24 09:36:59.692 UTC [orderer/consensus/kafka] startThread -> INFO 01e [channel: newchaincode] CONNECT message posted successfully
2021-01-24 09:36:59.692 UTC [orderer/consensus/kafka] setupParentConsumerForChannel -> INFO 01f [channel: newchaincode] Setting up the parent consumer for this channel...
2021-01-24 09:36:59.693 UTC [orderer/consensus/kafka] startThread -> INFO 020 [channel: newchaincode] Parent consumer set up successfully
2021-01-24 09:36:59.693 UTC [orderer/consensus/kafka] setupChannelConsumerForChannel -> INFO 021 [channel: newchaincode] Setting up the channel consumer for this channel (start offset: -2)...
2021-01-24 09:36:59.695 UTC [orderer/consensus/kafka] startThread -> INFO 022 [channel: newchaincode] Channel consumer set up successfully
2021-01-24 09:36:59.696 UTC [orderer/consensus/kafka] startThread -> INFO 023 [channel: newchaincode] Start phase completed successfully
2021-01-24 09:37:07.492 UTC [orderer/common/blockcutter] scheduleMsg -> INFO 024 Process msg 41cbecf6: snapshot=0, committed=1, readKeys=[newchaincode], writeKeys=[newchaincode]
2021-01-24 09:37:07.492 UTC [orderer/common/blockcutter/scheduler] func1 -> INFO 025 Action: Schedule Txn, Process Txn: 47 us
```
Peer Log:
```
2021-01-24 09:37:37.497 UTC [blocksProvider] DeliverBlocks -> INFO 045 Verifying Block 1 in 1 ms
2021-01-24 09:37:37.498 UTC [endorser] deliverPayloads -> INFO 046 Validate Block 1 0 ms
2021-01-24 09:37:37.498 UTC [gossip/privdata] StoreBlock -> INFO 047 [newchaincode] Received block [1] from buffer
2021-01-24 09:37:37.500 UTC [leveldbhelper] RetrieveLatestSnapshot -> INFO 048 Increment latest snapshot 0 to count &{1 842387647152}.
2021-01-24 09:37:37.500 UTC [leveldbhelper] ReleaseSnapshot -> INFO 049 Decrement snapshot 0 to count &{0 842387647152}. Latest Snapshot: 0
panic: Not supported...

goroutine 327 [running]:
github.com/hyperledger/fabric/core/ledger/kvledger/txmgmt/txmgr/snapshotbasedtxmgr.(*queryHelper).getStateMetadata(0xc422bb6840, 0xc422bb4568, 0x4, 0xc422bb4750, 0x9, 0x10, 0x108d7c0, 0x1)
	/opt/gopath/src/github.com/hyperledger/fabric/core/ledger/kvledger/txmgmt/txmgr/snapshotbasedtxmgr/helper.go:120 +0x39
github.com/hyperledger/fabric/core/ledger/kvledger/txmgmt/txmgr/snapshotbasedtxmgr.(*SnapshotBasedQueryExecutor).GetStateMetadata(0xc422bc43a0, 0xc422bb4568, 0x4, 0xc422bb4750, 0x9, 0xc4229fa700, 0x11e7480, 0xc42233ade8)
	/opt/gopath/src/github.com/hyperledger/fabric/core/ledger/kvledger/txmgmt/txmgr/snapshotbasedtxmgr/snapshotbased_query_executer.go:33 +0x56
github.com/hyperledger/fabric/core/common/validation/statebased.(*KeyLevelValidationParameterManagerImpl).GetValidationParameterForKey(0xc4229fb700, 0xc422bb4568, 0x4, 0x0, 0x0, 0xc422bb4750, 0x9, 0x1, 0x0, 0x0, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/core/common/validation/statebased/vpmanagerimpl.go:314 +0x377
github.com/hyperledger/fabric/core/common/validation/statebased.(*policyChecker).checkSBAndCCEP(0xc42233b2a8, 0xc422bb4568, 0x4, 0x0, 0x0, 0xc422bb4750, 0x9, 0x1, 0x0, 0x1052620, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/core/common/validation/statebased/validator_keylevel.go:61 +0xb4
github.com/hyperledger/fabric/core/common/validation/statebased.(*KeyLevelValidator).Validate(0xc422b83f90, 0xc422bb4568, 0x4, 0x1, 0x0, 0xc4205cb590, 0xe3, 0xf0, 0xc422bbc5a0, 0x1da, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/core/common/validation/statebased/validator_keylevel.go:240 +0x54f
github.com/hyperledger/fabric/core/handlers/validation/builtin/v13.(*Validator).Validate(0xc422bc8000, 0xc4229fae80, 0xc422bb4568, 0x4, 0x0, 0x0, 0xc4222afb20, 0x17, 0x17, 0xc422bc4220, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/core/handlers/validation/builtin/v13/validation_logic.go:164 +0x266
github.com/hyperledger/fabric/core/handlers/validation/builtin.(*DefaultValidation).Validate(0xc422bb6660, 0xc4229fae80, 0xc422bb4568, 0x4, 0x0, 0x0, 0xc422baedc0, 0x1, 0x1, 0xc4200a1d00, ...)
	/opt/gopath/src/github.com/hyperledger/fabric/core/handlers/validation/builtin/default_validation.go:68 +0x185
github.com/hyperledger/fabric/core/committer/txvalidator.(*PluginValidator).ValidateWithPlugin(0xc422517040, 0xc4222a6e80, 0x3, 0x3)
	/opt/gopath/src/github.com/hyperledger/fabric/core/committer/txvalidator/plugin_validator.go:99 +0x29f
github.com/hyperledger/fabric/core/committer/txvalidator.(*VsccValidatorImpl).VSCCValidateTxForCC(0xc4224b6d00, 0xc4222a6e80, 0xc422bb4568, 0x4)
	/opt/gopath/src/github.com/hyperledger/fabric/core/committer/txvalidator/vscc_validator.go:264 +0xc0
github.com/hyperledger/fabric/core/committer/txvalidator.(*VsccValidatorImpl).VSCCValidateTx(0xc4224b6d00, 0x0, 0xc4229faf40, 0xc422ba1600, 0xce3, 0xd80, 0xc4229fae80, 0x4, 0x60, 0x60)
	/opt/gopath/src/github.com/hyperledger/fabric/core/committer/txvalidator/vscc_validator.go:249 +0x1612
github.com/hyperledger/fabric/core/committer/txvalidator.(*TxValidator).validateTx(0xc42259c840, 0xc4201e3770, 0xc422b34780)
	/opt/gopath/src/github.com/hyperledger/fabric/core/committer/txvalidator/validator.go:359 +0xf48
github.com/hyperledger/fabric/core/committer/txvalidator.(*TxValidator).Validate.func1.1(0xc42259c840, 0xc4229fae80, 0xc422b34780, 0x0, 0xc422ba1600, 0xce3, 0xd80)
	/opt/gopath/src/github.com/hyperledger/fabric/core/committer/txvalidator/validator.go:158 +0xcb
created by github.com/hyperledger/fabric/core/committer/txvalidator.(*TxValidator).Validate.func1
	/opt/gopath/src/github.com/hyperledger/fabric/core/committer/txvalidator/validator.go:155 +0x109
```

**Comment by RUAN0007** [comment]
Hi, thank you for your interest. I believe your deployment may involve some additional features, such as private data collection. These additional features are not relevant to the transaction processing in the paper. So the branch does not support it.
